---

- import_tasks: config.yml
  tags:
    - system
    - apt
    - config
    - apt-config

- import_tasks: manage.yml
  tags:
    - system
    - apt
    - manage
    - apt-manage

- import_tasks: install.yml
  tags:
    - system
    - apt
    - install
    - apt-install
